/**
 * Seed: topics, subtopics, and real curated educational YouTube videos.
 * Run:  cd packages/db && npm run db:seed
 */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// ─── Topics ──────────────────────────────────────────────────────────────────

const TOPICS = [
  { name: "Programming",  slug: "programming",  emoji: "💻", color: "#2a4a7f", videoCount: 18400,
    subtopics: ["Python", "JavaScript", "Data Structures", "Web Development", "Machine Learning"] },
  { name: "Mathematics",  slug: "mathematics",  emoji: "∑",  color: "#1a4a3a", videoCount: 12300,
    subtopics: ["Calculus", "Linear Algebra", "Statistics", "Number Theory", "Discrete Math"] },
  { name: "Science",      slug: "science",      emoji: "🔬", color: "#1a5c35", videoCount: 24100,
    subtopics: ["Physics", "Biology", "Chemistry", "Neuroscience", "Astronomy"] },
  { name: "Philosophy",   slug: "philosophy",   emoji: "🦉", color: "#7a4010", videoCount: 7200,
    subtopics: ["Ethics", "Epistemology", "Stoicism", "Eastern Philosophy", "Logic"] },
  { name: "Finance",      slug: "finance",      emoji: "📈", color: "#3a2a6a", videoCount: 11800,
    subtopics: ["Investing", "Personal Finance", "Economics", "Crypto", "Accounting"] },
  { name: "History",      slug: "history",      emoji: "📜", color: "#8a5a00", videoCount: 8750,
    subtopics: ["World History", "Ancient Civilizations", "Modern History", "Wars & Empires"] },
  { name: "Music & Arts", slug: "music-arts",   emoji: "🎵", color: "#7a1040", videoCount: 9400,
    subtopics: ["Music Theory", "Guitar", "Piano", "Composition", "Art History"] },
  { name: "Languages",    slug: "languages",    emoji: "🗣️", color: "#10407a", videoCount: 13900,
    subtopics: ["Japanese", "Spanish", "French", "Mandarin", "Hindi"] },
  { name: "Design",       slug: "design-art",   emoji: "🎨", color: "#407a10", videoCount: 6600,
    subtopics: ["UI/UX", "Graphic Design", "Typography", "Product Design"] },
  { name: "Psychology",   slug: "psychology",   emoji: "🧠", color: "#6a1a6a", videoCount: 8100,
    subtopics: ["Cognitive Science", "Behavioral Psychology", "Mindfulness", "Social Psychology"] },
  { name: "Astronomy",    slug: "astronomy",    emoji: "🌌", color: "#0d0d4a", videoCount: 5400,
    subtopics: ["Cosmology", "Black Holes", "Planets", "Dark Matter", "Space Exploration"] },
  { name: "Engineering",  slug: "engineering",  emoji: "⚙️", color: "#107a7a", videoCount: 9200,
    subtopics: ["Civil Engineering", "Electrical Engineering", "Mechanical Engineering", "Computer Architecture"] },
];

// ─── Real educational YouTube videos ─────────────────────────────────────────

const VIDEOS = [
  // ── Programming ────────────────────────────────────────────────────────────
  {
    platformId: "rfscVS0vtbw",
    platform: "YOUTUBE" as const,
    title: "Learn Python - Full Course for Beginners [Tutorial]",
    description: "A full introduction into all of the core concepts in Python. Follow along and you'll be a Python programmer in no time.",
    channelName: "freeCodeCamp.org",
    thumbnailUrl: "https://i.ytimg.com/vi/rfscVS0vtbw/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=rfscVS0vtbw",
    embedUrl: "https://www.youtube.com/embed/rfscVS0vtbw",
    durationSeconds: 15720,
    viewCount: BigInt(32_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: true,
    aiSummary: "Complete Python from scratch — variables, data types, lists, functions, OOP, and file I/O.",
    topicSlugs: ["programming"],
  },
  {
    platformId: "_uQrJ0TkZlc",
    platform: "YOUTUBE" as const,
    title: "Python Tutorial - Python Full Course for Beginners",
    description: "Go from Zero to Hero with Python — includes machine learning & web development projects.",
    channelName: "Programming with Mosh",
    thumbnailUrl: "https://i.ytimg.com/vi/_uQrJ0TkZlc/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=_uQrJ0TkZlc",
    embedUrl: "https://www.youtube.com/embed/_uQrJ0TkZlc",
    durationSeconds: 21600,
    viewCount: BigInt(35_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Comprehensive 6-hour Python course with hands-on projects taught by Mosh Hamedani.",
    topicSlugs: ["programming"],
  },
  {
    platformId: "W6NZfCO5SIk",
    platform: "YOUTUBE" as const,
    title: "JavaScript Tutorial for Beginners: Learn JavaScript in 1 Hour",
    description: "Learn JavaScript from scratch in just 1 hour — the fastest JavaScript crash course.",
    channelName: "Programming with Mosh",
    thumbnailUrl: "https://i.ytimg.com/vi/W6NZfCO5SIk/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=W6NZfCO5SIk",
    embedUrl: "https://www.youtube.com/embed/W6NZfCO5SIk",
    durationSeconds: 4800,
    viewCount: BigInt(14_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Variables, conditionals, loops, functions, and objects — all the JavaScript fundamentals in one hour.",
    topicSlugs: ["programming"],
  },
  {
    platformId: "PkZNo7MFNFg",
    platform: "YOUTUBE" as const,
    title: "Learn JavaScript - Full Course for Beginners",
    description: "This complete 134-part JavaScript tutorial for beginners will teach you everything you need to know to get started with the JavaScript programming language.",
    channelName: "freeCodeCamp.org",
    thumbnailUrl: "https://i.ytimg.com/vi/PkZNo7MFNFg/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=PkZNo7MFNFg",
    embedUrl: "https://www.youtube.com/embed/PkZNo7MFNFg",
    durationSeconds: 10800,
    viewCount: BigInt(15_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Full 3-hour JavaScript course covering variables, arrays, objects, functions, DOM manipulation, and ES6+.",
    topicSlugs: ["programming"],
  },
  {
    platformId: "RGOj5yH7evk",
    platform: "YOUTUBE" as const,
    title: "Git and GitHub for Beginners - Crash Course",
    description: "Learn about Git and GitHub in this tutorial. These are important tools for all developers to understand. Git and GitHub make it easier to manage different software versions and make it easier for multiple people to work on the same software project.",
    channelName: "freeCodeCamp.org",
    thumbnailUrl: "https://i.ytimg.com/vi/RGOj5yH7evk/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=RGOj5yH7evk",
    embedUrl: "https://www.youtube.com/embed/RGOj5yH7evk",
    durationSeconds: 3720,
    viewCount: BigInt(8_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Master Git version control and GitHub — commits, branches, pull requests, and collaborative workflows.",
    topicSlugs: ["programming"],
  },
  {
    platformId: "Ke90Tje7VS0",
    platform: "YOUTUBE" as const,
    title: "React JS - React Tutorial for Beginners",
    description: "React tutorial for beginners - learn React.js in this step-by-step tutorial for beginners. We'll cover all the fundamentals of React including components, state, events, forms, etc.",
    channelName: "Programming with Mosh",
    thumbnailUrl: "https://i.ytimg.com/vi/Ke90Tje7VS0/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=Ke90Tje7VS0",
    embedUrl: "https://www.youtube.com/embed/Ke90Tje7VS0",
    durationSeconds: 5400,
    viewCount: BigInt(9_000_000),
    difficulty: "INTERMEDIATE" as const,
    isFeatured: false,
    aiSummary: "Build real React apps from scratch — components, state, props, hooks, and the React ecosystem.",
    topicSlugs: ["programming"],
  },

  // ── Mathematics ─────────────────────────────────────────────────────────────
  {
    platformId: "fNk_zzaMoSs",
    platform: "YOUTUBE" as const,
    title: "Vectors, what even are they? | Essence of linear algebra, Chapter 1",
    description: "Visual, intuitive linear algebra — what vectors truly are, how to add them, and how to scale them.",
    channelName: "3Blue1Brown",
    thumbnailUrl: "https://i.ytimg.com/vi/fNk_zzaMoSs/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=fNk_zzaMoSs",
    embedUrl: "https://www.youtube.com/embed/fNk_zzaMoSs",
    durationSeconds: 592,
    viewCount: BigInt(8_400_000),
    difficulty: "BEGINNER" as const,
    isFeatured: true,
    aiSummary: "A geometric, visual introduction to vectors — the foundation of all linear algebra.",
    topicSlugs: ["mathematics"],
  },
  {
    platformId: "WUvTyaaNkzM",
    platform: "YOUTUBE" as const,
    title: "The Essence of Calculus, Chapter 1",
    description: "Visual introduction to the core ideas of calculus — derivatives, integrals, and why they're connected.",
    channelName: "3Blue1Brown",
    thumbnailUrl: "https://i.ytimg.com/vi/WUvTyaaNkzM/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=WUvTyaaNkzM",
    embedUrl: "https://www.youtube.com/embed/WUvTyaaNkzM",
    durationSeconds: 1024,
    viewCount: BigInt(7_200_000),
    difficulty: "INTERMEDIATE" as const,
    isFeatured: true,
    aiSummary: "Derivatives, integrals, and the fundamental theorem of calculus — explained visually from first principles.",
    topicSlugs: ["mathematics"],
  },
  {
    platformId: "aircAruvnKk",
    platform: "YOUTUBE" as const,
    title: "But what is a neural network? | Deep learning, Chapter 1",
    description: "What are the neurons, what are they doing? An intuitive visual intro to neural networks.",
    channelName: "3Blue1Brown",
    thumbnailUrl: "https://i.ytimg.com/vi/aircAruvnKk/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=aircAruvnKk",
    embedUrl: "https://www.youtube.com/embed/aircAruvnKk",
    durationSeconds: 1153,
    viewCount: BigInt(14_200_000),
    difficulty: "INTERMEDIATE" as const,
    isFeatured: true,
    aiSummary: "A visual, intuitive introduction to neural networks — how neurons, layers, and weights work together to learn.",
    topicSlugs: ["mathematics", "programming"],
  },
  {
    platformId: "spUNpyF58BY",
    platform: "YOUTUBE" as const,
    title: "But what is the Fourier Transform? A visual introduction.",
    description: "An animated introduction to the Fourier transform, winding graphs around circles.",
    channelName: "3Blue1Brown",
    thumbnailUrl: "https://i.ytimg.com/vi/spUNpyF58BY/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=spUNpyF58BY",
    embedUrl: "https://www.youtube.com/embed/spUNpyF58BY",
    durationSeconds: 1260,
    viewCount: BigInt(10_000_000),
    difficulty: "INTERMEDIATE" as const,
    isFeatured: false,
    aiSummary: "A stunning visual explanation of the Fourier Transform — how any signal can be decomposed into sine waves.",
    topicSlugs: ["mathematics"],
  },
  {
    platformId: "HZGCoVF3YvM",
    platform: "YOUTUBE" as const,
    title: "Bayes theorem, the geometry of changing beliefs",
    description: "An introduction to Bayes' theorem — how to update beliefs in light of new evidence.",
    channelName: "3Blue1Brown",
    thumbnailUrl: "https://i.ytimg.com/vi/HZGCoVF3YvM/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=HZGCoVF3YvM",
    embedUrl: "https://www.youtube.com/embed/HZGCoVF3YvM",
    durationSeconds: 900,
    viewCount: BigInt(5_500_000),
    difficulty: "INTERMEDIATE" as const,
    isFeatured: false,
    aiSummary: "Bayes theorem explained geometrically — how to rationally update your beliefs when you get new evidence.",
    topicSlugs: ["mathematics"],
  },
  {
    platformId: "OkmNXy7er84",
    platform: "YOUTUBE" as const,
    title: "Statistics - A Full University Course on Data Science Basics",
    description: "Learn the essentials of statistics in this complete course. This course teaches you the core concepts and helps you master statistics step-by-step.",
    channelName: "freeCodeCamp.org",
    thumbnailUrl: "https://i.ytimg.com/vi/OkmNXy7er84/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=OkmNXy7er84",
    embedUrl: "https://www.youtube.com/embed/OkmNXy7er84",
    durationSeconds: 25200,
    viewCount: BigInt(2_500_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Full university-level statistics course — descriptive stats, probability, distributions, hypothesis testing, regression.",
    topicSlugs: ["mathematics"],
  },

  // ── Science ─────────────────────────────────────────────────────────────────
  {
    platformId: "h6fcK_fRYaI",
    platform: "YOUTUBE" as const,
    title: "The Egg - A Short Story",
    description: "A beautifully animated philosophical short — about consciousness, existence, and what it means to be human.",
    channelName: "Kurzgesagt – In a Nutshell",
    thumbnailUrl: "https://i.ytimg.com/vi/h6fcK_fRYaI/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=h6fcK_fRYaI",
    embedUrl: "https://www.youtube.com/embed/h6fcK_fRYaI",
    durationSeconds: 490,
    viewCount: BigInt(25_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: true,
    aiSummary: "A profound animated short about consciousness, reincarnation, and the interconnectedness of all humans.",
    topicSlugs: ["science", "philosophy"],
  },
  {
    platformId: "QsBT5EQt348",
    platform: "YOUTUBE" as const,
    title: "Overpopulation – The Human Explosion Explained",
    description: "In a world of 7 billion people and counting, is overpopulation really the problem we think it is?",
    channelName: "Kurzgesagt – In a Nutshell",
    thumbnailUrl: "https://i.ytimg.com/vi/QsBT5EQt348/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=QsBT5EQt348",
    embedUrl: "https://www.youtube.com/embed/QsBT5EQt348",
    durationSeconds: 360,
    viewCount: BigInt(18_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Explores the real data behind population growth and what it actually means for humanity's future.",
    topicSlugs: ["science"],
  },
  {
    platformId: "zQGOcOUBi6s",
    platform: "YOUTUBE" as const,
    title: "The Immune System Explained I – Bacteria Infection",
    description: "Every second of your life you are under attack — bacteria, viruses, and parasites try to invade your body. But most of the time you feel fine. So what's protecting you?",
    channelName: "Kurzgesagt – In a Nutshell",
    thumbnailUrl: "https://i.ytimg.com/vi/zQGOcOUBi6s/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=zQGOcOUBi6s",
    embedUrl: "https://www.youtube.com/embed/zQGOcOUBi6s",
    durationSeconds: 420,
    viewCount: BigInt(13_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "How your immune system fights bacteria — the front-line defenders, the inflammatory response, and why it works.",
    topicSlugs: ["science"],
  },
  {
    platformId: "Da-2h3F5a18",
    platform: "YOUTUBE" as const,
    title: "String Theory Explained – What is The True Nature of Reality?",
    description: "Is String Theory the final theory of everything — or just a beautiful mathematical fantasy?",
    channelName: "Kurzgesagt – In a Nutshell",
    thumbnailUrl: "https://i.ytimg.com/vi/Da-2h3F5a18/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=Da-2h3F5a18",
    embedUrl: "https://www.youtube.com/embed/Da-2h3F5a18",
    durationSeconds: 480,
    viewCount: BigInt(9_000_000),
    difficulty: "INTERMEDIATE" as const,
    isFeatured: false,
    aiSummary: "A clear breakdown of string theory — extra dimensions, vibrating strings, and why physicists find it so compelling.",
    topicSlugs: ["science", "astronomy"],
  },
  {
    platformId: "ZM8ECpBuQYE",
    platform: "YOUTUBE" as const,
    title: "Motion in a Straight Line: Crash Course Physics #1",
    description: "In this, THE FIRST EPISODE of Crash Course Physics, your host Dr. Shini Somara introduces us to the ideas of motion in a straight line.",
    channelName: "CrashCourse",
    thumbnailUrl: "https://i.ytimg.com/vi/ZM8ECpBuQYE/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=ZM8ECpBuQYE",
    embedUrl: "https://www.youtube.com/embed/ZM8ECpBuQYE",
    durationSeconds: 540,
    viewCount: BigInt(3_500_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Introduction to kinematics — displacement, velocity, acceleration, and equations of motion.",
    topicSlugs: ["science"],
  },
  {
    platformId: "MBRqu0YOH14",
    platform: "YOUTUBE" as const,
    title: "Optimistic Nihilism",
    description: "How to make the most out of a meaningless universe — an optimistic take on nihilism.",
    channelName: "Kurzgesagt – In a Nutshell",
    thumbnailUrl: "https://i.ytimg.com/vi/MBRqu0YOH14/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=MBRqu0YOH14",
    embedUrl: "https://www.youtube.com/embed/MBRqu0YOH14",
    durationSeconds: 420,
    viewCount: BigInt(16_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "A life-affirming take on existential philosophy — why the universe's indifference can actually be liberating.",
    topicSlugs: ["science", "philosophy"],
  },

  // ── Philosophy ──────────────────────────────────────────────────────────────
  {
    platformId: "qp0HIF3SfI4",
    platform: "YOUTUBE" as const,
    title: "How great leaders inspire action | Simon Sinek",
    description: "Simon Sinek presents a simple but powerful model for how leaders inspire cooperation, trust, and change. It all starts with Why.",
    channelName: "TED",
    thumbnailUrl: "https://i.ytimg.com/vi/qp0HIF3SfI4/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=qp0HIF3SfI4",
    embedUrl: "https://www.youtube.com/embed/qp0HIF3SfI4",
    durationSeconds: 1081,
    viewCount: BigInt(68_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: true,
    aiSummary: "Simon Sinek's 'Start With Why' framework — why great leaders and organizations think from the inside out.",
    topicSlugs: ["philosophy", "finance"],
  },
  {
    platformId: "iG9CE55wbtY",
    platform: "YOUTUBE" as const,
    title: "Do schools kill creativity? | Sir Ken Robinson",
    description: "Sir Ken Robinson makes an entertaining and profoundly moving case for creating an education system that nurtures creativity.",
    channelName: "TED",
    thumbnailUrl: "https://i.ytimg.com/vi/iG9CE55wbtY/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=iG9CE55wbtY",
    embedUrl: "https://www.youtube.com/embed/iG9CE55wbtY",
    durationSeconds: 1165,
    viewCount: BigInt(74_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: true,
    aiSummary: "The most-watched TED talk ever — a compelling argument that schools systematically destroy children's creativity.",
    topicSlugs: ["philosophy"],
  },
  {
    platformId: "iCvmsMzlF7o",
    platform: "YOUTUBE" as const,
    title: "The Power of Vulnerability | Brené Brown",
    description: "Brené Brown studies human connection — our ability to empathize, belong, and love. In a talk that has 63M views.",
    channelName: "TED",
    thumbnailUrl: "https://i.ytimg.com/vi/iCvmsMzlF7o/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=iCvmsMzlF7o",
    embedUrl: "https://www.youtube.com/embed/iCvmsMzlF7o",
    durationSeconds: 1219,
    viewCount: BigInt(63_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Brené Brown on vulnerability, shame, connection, and why embracing imperfection is the key to belonging.",
    topicSlugs: ["philosophy", "psychology"],
  },
  {
    platformId: "arj7oStGLkU",
    platform: "YOUTUBE" as const,
    title: "Inside the mind of a master procrastinator | Tim Urban",
    description: "Tim Urban knows that procrastination doesn't make sense, but he's still done it his whole life. Here's a hilarious deep-dive.",
    channelName: "TED",
    thumbnailUrl: "https://i.ytimg.com/vi/arj7oStGLkU/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=arj7oStGLkU",
    embedUrl: "https://www.youtube.com/embed/arj7oStGLkU",
    durationSeconds: 844,
    viewCount: BigInt(60_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Tim Urban's hilarious breakdown of the procrastinator's brain — the Instant Gratification Monkey, the Rational Decision-Maker, and the Panic Monster.",
    topicSlugs: ["philosophy", "psychology"],
  },
  {
    platformId: "VO6XEQIsCoM",
    platform: "YOUTUBE" as const,
    title: "The Paradox of Choice – Why More Is Less | Barry Schwartz",
    description: "Psychologist Barry Schwartz takes aim at a central tenet of western societies: freedom of choice. In Schwartz's estimation, choice has made us not freer but more paralyzed, not happier but more dissatisfied.",
    channelName: "TED",
    thumbnailUrl: "https://i.ytimg.com/vi/VO6XEQIsCoM/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=VO6XEQIsCoM",
    embedUrl: "https://www.youtube.com/embed/VO6XEQIsCoM",
    durationSeconds: 1140,
    viewCount: BigInt(15_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Why having too many choices makes us less satisfied — the psychological cost of an abundance of options.",
    topicSlugs: ["philosophy", "psychology"],
  },
  {
    platformId: "GEmuEWjHr5c",
    platform: "YOUTUBE" as const,
    title: "PHILOSOPHY - Aristotle",
    description: "Aristotle was one of the greatest philosophers who ever lived. A guide to his thought.",
    channelName: "The School of Life",
    thumbnailUrl: "https://i.ytimg.com/vi/GEmuEWjHr5c/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=GEmuEWjHr5c",
    embedUrl: "https://www.youtube.com/embed/GEmuEWjHr5c",
    durationSeconds: 540,
    viewCount: BigInt(4_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "A clear, engaging introduction to Aristotle's key ideas — virtue ethics, eudaimonia, the golden mean, and logic.",
    topicSlugs: ["philosophy"],
  },

  // ── Finance ─────────────────────────────────────────────────────────────────
  {
    platformId: "p7HKvqRI_Bo",
    platform: "YOUTUBE" as const,
    title: "How does the stock market work? - Oliver Elfenbaum",
    description: "The invention of the stock market is one of the most crucial developments in the history of commerce.",
    channelName: "TED-Ed",
    thumbnailUrl: "https://i.ytimg.com/vi/p7HKvqRI_Bo/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=p7HKvqRI_Bo",
    embedUrl: "https://www.youtube.com/embed/p7HKvqRI_Bo",
    durationSeconds: 240,
    viewCount: BigInt(17_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "A crisp 4-minute explanation of how stock markets work — stocks, IPOs, dividends, and why markets rise and fall.",
    topicSlugs: ["finance"],
  },
  {
    platformId: "PHe0bXAIuk0",
    platform: "YOUTUBE" as const,
    title: "How The Economic Machine Works by Ray Dalio",
    description: "A 30 minute animated video that simply and clearly explains how the economy works and what principles guide it, by Ray Dalio.",
    channelName: "Ray Dalio",
    thumbnailUrl: "https://i.ytimg.com/vi/PHe0bXAIuk0/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=PHe0bXAIuk0",
    embedUrl: "https://www.youtube.com/embed/PHe0bXAIuk0",
    durationSeconds: 1800,
    viewCount: BigInt(30_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: true,
    aiSummary: "Ray Dalio's animated masterclass on economics — credit cycles, debt crises, and how the economic machine works.",
    topicSlugs: ["finance"],
  },
  {
    platformId: "3ez10ADR_gM",
    platform: "YOUTUBE" as const,
    title: "Intro to Economics: Crash Course Econ #1",
    description: "In which Jacob Clifford and Adriene Hill launch a brand new Crash Course on Economics! So, what is economics?",
    channelName: "CrashCourse",
    thumbnailUrl: "https://i.ytimg.com/vi/3ez10ADR_gM/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=3ez10ADR_gM",
    embedUrl: "https://www.youtube.com/embed/3ez10ADR_gM",
    durationSeconds: 480,
    viewCount: BigInt(5_500_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "What is economics, why does it matter, and what can it tell us about human decision-making and resource allocation?",
    topicSlugs: ["finance"],
  },
  {
    platformId: "fOrBKiOH0vs",
    platform: "YOUTUBE" as const,
    title: "Warren Buffett: On How To Pick Stocks and Invest Properly",
    description: "Warren Buffett shares his wisdom on how to pick stocks and how to invest properly for long-term wealth.",
    channelName: "CNBC",
    thumbnailUrl: "https://i.ytimg.com/vi/fOrBKiOH0vs/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=fOrBKiOH0vs",
    embedUrl: "https://www.youtube.com/embed/fOrBKiOH0vs",
    durationSeconds: 780,
    viewCount: BigInt(4_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Warren Buffett's principles for picking stocks — value investing, long-term thinking, and understanding a business.",
    topicSlugs: ["finance"],
  },

  // ── History ──────────────────────────────────────────────────────────────────
  {
    platformId: "xuCn8ux2gbs",
    platform: "YOUTUBE" as const,
    title: "history of the entire world, i guess",
    description: "patreon: https://www.patreon.com/billwurtz — all of history from the Big Bang to today.",
    channelName: "bill wurtz",
    thumbnailUrl: "https://i.ytimg.com/vi/xuCn8ux2gbs/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=xuCn8ux2gbs",
    embedUrl: "https://www.youtube.com/embed/xuCn8ux2gbs",
    durationSeconds: 1165,
    viewCount: BigInt(112_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: true,
    aiSummary: "The entire history of the world from the Big Bang to today — in under 20 minutes, somehow accurate and extremely entertaining.",
    topicSlugs: ["history"],
  },
  {
    platformId: "Yocja_N5s1I",
    platform: "YOUTUBE" as const,
    title: "The Agricultural Revolution: Crash Course World History #1",
    description: "John Green teaches you about the agricultural revolution and the invention of farming.",
    channelName: "CrashCourse",
    thumbnailUrl: "https://i.ytimg.com/vi/Yocja_N5s1I/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=Yocja_N5s1I",
    embedUrl: "https://www.youtube.com/embed/Yocja_N5s1I",
    durationSeconds: 630,
    viewCount: BigInt(11_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "How farming transformed human civilization — and why early farmers may actually have had it worse than hunters.",
    topicSlugs: ["history"],
  },
  {
    platformId: "Mh5LY4Mz15o",
    platform: "YOUTUBE" as const,
    title: "history of japan",
    description: "hi welcome to the history of japan.",
    channelName: "bill wurtz",
    thumbnailUrl: "https://i.ytimg.com/vi/Mh5LY4Mz15o/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=Mh5LY4Mz15o",
    embedUrl: "https://www.youtube.com/embed/Mh5LY4Mz15o",
    durationSeconds: 540,
    viewCount: BigInt(70_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Japan's entire history in 9 minutes — islands, emperors, samurai, shoguns, Meiji Restoration, WWII, and modern Japan.",
    topicSlugs: ["history"],
  },
  {
    platformId: "_uk_6vfYy64",
    platform: "YOUTUBE" as const,
    title: "WW2 - OverSimplified (Part 1)",
    description: "The first part of OverSimplified's World War 2 series — covering the rise of fascism, the invasion of Poland, and the early war.",
    channelName: "OverSimplified",
    thumbnailUrl: "https://i.ytimg.com/vi/_uk_6vfYy64/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=_uk_6vfYy64",
    embedUrl: "https://www.youtube.com/embed/_uk_6vfYy64",
    durationSeconds: 960,
    viewCount: BigInt(30_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "World War 2 simplified but not dumbed down — the causes, key players, and opening moves of history's deadliest conflict.",
    topicSlugs: ["history"],
  },
  {
    platformId: "n7ndRwqJYDM",
    platform: "YOUTUBE" as const,
    title: "The Roman Empire. Or Republic. Or...Which Was It?: Crash Course World History #10",
    description: "John Green explains the Roman Empire — or was it a Republic? In which John discusses the Roman Republic and the Roman Empire, their rise and fall, and their enduring legacy.",
    channelName: "CrashCourse",
    thumbnailUrl: "https://i.ytimg.com/vi/n7ndRwqJYDM/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=n7ndRwqJYDM",
    embedUrl: "https://www.youtube.com/embed/n7ndRwqJYDM",
    durationSeconds: 660,
    viewCount: BigInt(8_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "The rise and fall of Rome — from Republic to Empire, Julius Caesar, Augustus, the legions, and the lasting legacy.",
    topicSlugs: ["history"],
  },

  // ── Music & Arts ─────────────────────────────────────────────────────────────
  {
    platformId: "R0JKCYZ8hng",
    platform: "YOUTUBE" as const,
    title: "How playing an instrument benefits your brain - Anita Collins",
    description: "When you listen to music, multiple areas of your brain become engaged and active. But when you actually play an instrument, that activity becomes more like a full-body brain workout.",
    channelName: "TED-Ed",
    thumbnailUrl: "https://i.ytimg.com/vi/R0JKCYZ8hng/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=R0JKCYZ8hng",
    embedUrl: "https://www.youtube.com/embed/R0JKCYZ8hng",
    durationSeconds: 300,
    viewCount: BigInt(14_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: true,
    aiSummary: "Playing a musical instrument is like a full-body brain workout — boosting memory, coordination, and emotional processing.",
    topicSlugs: ["music-arts"],
  },
  {
    platformId: "r9LCwI5iErE",
    platform: "YOUTUBE" as const,
    title: "The transformative power of classical music | Benjamin Zander",
    description: "Benjamin Zander has two infectious passions: classical music, and helping us all realize our untapped love for it — and for theopen-eyed, rapt attention classical music demands.",
    channelName: "TED",
    thumbnailUrl: "https://i.ytimg.com/vi/r9LCwI5iErE/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=r9LCwI5iErE",
    embedUrl: "https://www.youtube.com/embed/r9LCwI5iErE",
    durationSeconds: 1140,
    viewCount: BigInt(10_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Benjamin Zander makes an irresistible case for classical music — how one note can change everything you hear.",
    topicSlugs: ["music-arts"],
  },
  {
    platformId: "i_0DXxqyna",
    platform: "YOUTUBE" as const,
    title: "Music Theory Fundamentals",
    description: "Learn the fundamentals of music theory — notes, scales, chords, rhythm, and how they all fit together.",
    channelName: "12tone",
    thumbnailUrl: "https://i.ytimg.com/vi/i_0DXxqyna/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=i_0DXxqyna",
    embedUrl: "https://www.youtube.com/embed/i_0DXxqyna",
    durationSeconds: 720,
    viewCount: BigInt(1_500_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Music theory from scratch — the building blocks of melody, harmony, and rhythm that every musician should understand.",
    topicSlugs: ["music-arts"],
  },
  {
    platformId: "lvmqpVPo1EM",
    platform: "YOUTUBE" as const,
    title: "Art History: A Very Short Introduction",
    description: "An accessible overview of art history from cave paintings to contemporary art.",
    channelName: "Oxford Academic",
    thumbnailUrl: "https://i.ytimg.com/vi/lvmqpVPo1EM/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=lvmqpVPo1EM",
    embedUrl: "https://www.youtube.com/embed/lvmqpVPo1EM",
    durationSeconds: 540,
    viewCount: BigInt(500_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Art history in a nutshell — from ancient cave paintings through Renaissance, Impressionism, to contemporary art movements.",
    topicSlugs: ["music-arts"],
  },

  // ── Languages ────────────────────────────────────────────────────────────────
  {
    platformId: "d0yGdNEWdn0",
    platform: "YOUTUBE" as const,
    title: "How to learn any language in six months | Chris Lonsdale | TEDxLingnanUniversity",
    description: "Chris Lonsdale is a psychologist and business consultant who has spent the last 30 years figuring out how people learn — and how anyone can become fluent in a second language in just 6 months.",
    channelName: "TEDx Talks",
    thumbnailUrl: "https://i.ytimg.com/vi/d0yGdNEWdn0/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=d0yGdNEWdn0",
    embedUrl: "https://www.youtube.com/embed/d0yGdNEWdn0",
    durationSeconds: 1080,
    viewCount: BigInt(35_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: true,
    aiSummary: "The 5 principles and 7 actions proven to help you learn any language in 6 months — used by linguists and polyglots worldwide.",
    topicSlugs: ["languages"],
  },
  {
    platformId: "MMmOLN5zBLY",
    platform: "YOUTUBE" as const,
    title: "The benefits of a bilingual brain - Mia Nacamulli",
    description: "It's obvious that knowing more than one language can make certain things easier — like traveling or watching films without subtitles. But are there other advantages to having a bilingual (or multilingual) brain?",
    channelName: "TED-Ed",
    thumbnailUrl: "https://i.ytimg.com/vi/MMmOLN5zBLY/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=MMmOLN5zBLY",
    embedUrl: "https://www.youtube.com/embed/MMmOLN5zBLY",
    durationSeconds: 300,
    viewCount: BigInt(13_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "The science of bilingualism — how speaking two languages reshapes the brain and boosts cognitive flexibility.",
    topicSlugs: ["languages"],
  },
  {
    platformId: "aZke6Va9_mE",
    platform: "YOUTUBE" as const,
    title: "Learn Spanish in 4 Hours - ALL the Spanish Basics You Need",
    description: "Learn Spanish fast! This 4-hour Spanish course for beginners covers the most important vocabulary, phrases, and grammar rules.",
    channelName: "SpanishPod101.com",
    thumbnailUrl: "https://i.ytimg.com/vi/aZke6Va9_mE/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=aZke6Va9_mE",
    embedUrl: "https://www.youtube.com/embed/aZke6Va9_mE",
    durationSeconds: 14400,
    viewCount: BigInt(3_500_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Complete Spanish basics in 4 hours — pronunciation, essential vocabulary, common phrases, and basic grammar.",
    topicSlugs: ["languages"],
  },
  {
    platformId: "6fj3oRCmj8E",
    platform: "YOUTUBE" as const,
    title: "Learn Japanese in 4 Hours - ALL the Japanese Basics for Beginners",
    description: "Learn the basics of Japanese fast! This course covers hiragana, katakana, vocabulary, and essential phrases for beginners.",
    channelName: "JapanesePod101.com",
    thumbnailUrl: "https://i.ytimg.com/vi/6fj3oRCmj8E/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=6fj3oRCmj8E",
    embedUrl: "https://www.youtube.com/embed/6fj3oRCmj8E",
    durationSeconds: 14400,
    viewCount: BigInt(2_500_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Japanese essentials for absolute beginners — writing systems, pronunciation, greetings, and everyday vocabulary.",
    topicSlugs: ["languages"],
  },

  // ── Design ────────────────────────────────────────────────────────────────────
  {
    platformId: "YqQx75OPRa0",
    platform: "YOUTUBE" as const,
    title: "Beginning Graphic Design: Fundamentals",
    description: "Learn about the fundamental principles of good design — from color and typography to layout and visual hierarchy.",
    channelName: "GCFLearnFree.org",
    thumbnailUrl: "https://i.ytimg.com/vi/YqQx75OPRa0/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=YqQx75OPRa0",
    embedUrl: "https://www.youtube.com/embed/YqQx75OPRa0",
    durationSeconds: 360,
    viewCount: BigInt(3_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: true,
    aiSummary: "The core principles of graphic design — balance, contrast, alignment, repetition, and proximity — explained clearly.",
    topicSlugs: ["design-art"],
  },
  {
    platformId: "UAinLaT42xo",
    platform: "YOUTUBE" as const,
    title: "Designers – think big! | Tim Brown",
    description: "Tim Brown argues that design thinking should be applied to global challenges, not just product design. It's a call to designers to think big.",
    channelName: "TED",
    thumbnailUrl: "https://i.ytimg.com/vi/UAinLaT42xo/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=UAinLaT42xo",
    embedUrl: "https://www.youtube.com/embed/UAinLaT42xo",
    durationSeconds: 1020,
    viewCount: BigInt(2_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "IDEO's Tim Brown on Design Thinking — human-centered design as a methodology for solving complex problems.",
    topicSlugs: ["design-art"],
  },
  {
    platformId: "c9Wg6Cb_YlU",
    platform: "YOUTUBE" as const,
    title: "UI Design Tutorial – Figma for Beginners",
    description: "Learn Figma and UI design from scratch in this beginner-friendly tutorial. Covers components, auto-layout, and design systems.",
    channelName: "DesignCourse",
    thumbnailUrl: "https://i.ytimg.com/vi/c9Wg6Cb_YlU/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=c9Wg6Cb_YlU",
    embedUrl: "https://www.youtube.com/embed/c9Wg6Cb_YlU",
    durationSeconds: 3600,
    viewCount: BigInt(2_500_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Figma UI design for beginners — frames, components, auto-layout, prototyping, and building your first design system.",
    topicSlugs: ["design-art"],
  },
  {
    platformId: "sByzHoiYFX0",
    platform: "YOUTUBE" as const,
    title: "Beginning Graphic Design: Typography",
    description: "Typography is one of the most important elements in design. In this video, you'll learn the basics of working with type.",
    channelName: "GCFLearnFree.org",
    thumbnailUrl: "https://i.ytimg.com/vi/sByzHoiYFX0/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=sByzHoiYFX0",
    embedUrl: "https://www.youtube.com/embed/sByzHoiYFX0",
    durationSeconds: 300,
    viewCount: BigInt(2_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Typography essentials — typefaces, hierarchy, readability, and how type choices affect the feel of any design.",
    topicSlugs: ["design-art"],
  },

  // ── Psychology ───────────────────────────────────────────────────────────────
  {
    platformId: "Ks-_Mh1QhMc",
    platform: "YOUTUBE" as const,
    title: "Your body language may shape who you are | Amy Cuddy",
    description: "Body language affects how others see us, but it may also change how we see ourselves. Social psychologist Amy Cuddy argues that 'power posing' — standing in a posture of confidence — can affect testosterone and cortisol levels in the brain.",
    channelName: "TED",
    thumbnailUrl: "https://i.ytimg.com/vi/Ks-_Mh1QhMc/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=Ks-_Mh1QhMc",
    embedUrl: "https://www.youtube.com/embed/Ks-_Mh1QhMc",
    durationSeconds: 1260,
    viewCount: BigInt(65_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: true,
    aiSummary: "Amy Cuddy on body language and power — how posture changes hormones, confidence, and how others perceive you.",
    topicSlugs: ["psychology"],
  },
  {
    platformId: "z-IR48Mb3W0",
    platform: "YOUTUBE" as const,
    title: "What is depression? - Helen M. Farrell",
    description: "Depression is the leading cause of disability worldwide, and it's distinct from the normal lows that come and go with everyday life.",
    channelName: "TED-Ed",
    thumbnailUrl: "https://i.ytimg.com/vi/z-IR48Mb3W0/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=z-IR48Mb3W0",
    embedUrl: "https://www.youtube.com/embed/z-IR48Mb3W0",
    durationSeconds: 300,
    viewCount: BigInt(12_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "A clear, compassionate explanation of clinical depression — its biology, symptoms, and modern treatment approaches.",
    topicSlugs: ["psychology"],
  },
  {
    platformId: "WuyPuH9ojCE",
    platform: "YOUTUBE" as const,
    title: "How stress affects your brain - Madhumita Murgia",
    description: "Stress isn't always a bad thing — it can be handy for a burst of extra energy and focus. But what happens when the rush doesn't go away?",
    channelName: "TED-Ed",
    thumbnailUrl: "https://i.ytimg.com/vi/WuyPuH9ojCE/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=WuyPuH9ojCE",
    embedUrl: "https://www.youtube.com/embed/WuyPuH9ojCE",
    durationSeconds: 240,
    viewCount: BigInt(18_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "The neuroscience of chronic stress — how cortisol damages the brain, shrinks the hippocampus, and affects memory.",
    topicSlugs: ["psychology"],
  },
  {
    platformId: "UyyjU8fzEYU",
    platform: "YOUTUBE" as const,
    title: "The Psychology of Self-Motivation | Scott Geller | TEDxVirginiaTech",
    description: "Scott Geller describes what it takes to be a self-motivated individual and how you can feel empowered to change behavior for the better.",
    channelName: "TEDx Talks",
    thumbnailUrl: "https://i.ytimg.com/vi/UyyjU8fzEYU/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=UyyjU8fzEYU",
    embedUrl: "https://www.youtube.com/embed/UyyjU8fzEYU",
    durationSeconds: 960,
    viewCount: BigInt(3_500_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "The science of self-motivation — choice, competence, and community as the three pillars of intrinsic motivation.",
    topicSlugs: ["psychology"],
  },

  // ── Astronomy ────────────────────────────────────────────────────────────────
  {
    platformId: "e-P5IFTqB98",
    platform: "YOUTUBE" as const,
    title: "Black Holes Explained – From Birth to Death",
    description: "Black holes are among the most mysterious and fascinating objects in the universe. From stellar-mass black holes to supermassive giants, learn how they form and what happens inside.",
    channelName: "Kurzgesagt – In a Nutshell",
    thumbnailUrl: "https://i.ytimg.com/vi/e-P5IFTqB98/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=e-P5IFTqB98",
    embedUrl: "https://www.youtube.com/embed/e-P5IFTqB98",
    durationSeconds: 480,
    viewCount: BigInt(11_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: true,
    aiSummary: "Everything about black holes — how they form from dying stars, what happens at the event horizon, and how they die.",
    topicSlugs: ["astronomy"],
  },
  {
    platformId: "udFxKZRyQt4",
    platform: "YOUTUBE" as const,
    title: "Neutron Stars – The Most Extreme Things that are not Black Holes",
    description: "Neutron stars are one of the most extreme and violent things in the universe. They are created when a massive star explodes in a supernova.",
    channelName: "Kurzgesagt – In a Nutshell",
    thumbnailUrl: "https://i.ytimg.com/vi/udFxKZRyQt4/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=udFxKZRyQt4",
    embedUrl: "https://www.youtube.com/embed/udFxKZRyQt4",
    durationSeconds: 420,
    viewCount: BigInt(9_000_000),
    difficulty: "INTERMEDIATE" as const,
    isFeatured: false,
    aiSummary: "Neutron stars explained — pulsars, magnetars, the exotic matter inside them, and what happens when two collide.",
    topicSlugs: ["astronomy"],
  },
  {
    platformId: "CWulQ1ZSE3c",
    platform: "YOUTUBE" as const,
    title: "The Life of a Star – From Stellar Nursery to Supernova",
    description: "Stars are born, live, and die — discover the full life cycle of a star, from molecular cloud to white dwarf, neutron star, or black hole.",
    channelName: "Kurzgesagt – In a Nutshell",
    thumbnailUrl: "https://i.ytimg.com/vi/CWulQ1ZSE3c/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=CWulQ1ZSE3c",
    embedUrl: "https://www.youtube.com/embed/CWulQ1ZSE3c",
    durationSeconds: 480,
    viewCount: BigInt(6_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "The complete life cycle of a star — stellar nurseries, main sequence, red giants, supernovae, and final remnants.",
    topicSlugs: ["astronomy"],
  },
  {
    platformId: "HdPzOWlLrbE",
    platform: "YOUTUBE" as const,
    title: "Cosmos: A Spacetime Odyssey — Standing Up in the Milky Way",
    description: "Neil deGrasse Tyson takes us on a voyage through space and time to discover our place in the universe.",
    channelName: "National Geographic",
    thumbnailUrl: "https://i.ytimg.com/vi/HdPzOWlLrbE/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=HdPzOWlLrbE",
    embedUrl: "https://www.youtube.com/embed/HdPzOWlLrbE",
    durationSeconds: 2700,
    viewCount: BigInt(3_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Neil deGrasse Tyson's cosmic journey — from the Big Bang to the formation of Earth and humanity's place in the universe.",
    topicSlugs: ["astronomy"],
  },

  // ── Engineering ──────────────────────────────────────────────────────────────
  {
    platformId: "cNN_tTXABUA",
    platform: "YOUTUBE" as const,
    title: "How a CPU Works",
    description: "How do processors work? What actually happens inside a CPU? This video explains everything from transistors to instruction sets.",
    channelName: "In One Lesson",
    thumbnailUrl: "https://i.ytimg.com/vi/cNN_tTXABUA/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=cNN_tTXABUA",
    embedUrl: "https://www.youtube.com/embed/cNN_tTXABUA",
    durationSeconds: 660,
    viewCount: BigInt(5_000_000),
    difficulty: "INTERMEDIATE" as const,
    isFeatured: true,
    aiSummary: "Inside a CPU — transistors, logic gates, the ALU, clock cycles, and how billions of operations happen per second.",
    topicSlugs: ["engineering", "programming"],
  },
  {
    platformId: "btGCi7JdhgY",
    platform: "YOUTUBE" as const,
    title: "What Is Engineering? - Crash Course Engineering #1",
    description: "Engineering is everywhere. It shapes the world we live in. But what IS engineering, exactly? Crash Course explains.",
    channelName: "CrashCourse",
    thumbnailUrl: "https://i.ytimg.com/vi/btGCi7JdhgY/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=btGCi7JdhgY",
    embedUrl: "https://www.youtube.com/embed/btGCi7JdhgY",
    durationSeconds: 420,
    viewCount: BigInt(1_500_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Engineering fundamentals and the design process — how engineers identify problems and build solutions that shape our world.",
    topicSlugs: ["engineering"],
  },
  {
    platformId: "zOjov-2OZ0E",
    platform: "YOUTUBE" as const,
    title: "How do Solar Panels Work? - Richard Komp",
    description: "The Earth receives about 173,000 terawatts of solar energy continuously — more than 10,000 times the world's total energy use. How do we harness it?",
    channelName: "TED-Ed",
    thumbnailUrl: "https://i.ytimg.com/vi/zOjov-2OZ0E/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=zOjov-2OZ0E",
    embedUrl: "https://www.youtube.com/embed/zOjov-2OZ0E",
    durationSeconds: 300,
    viewCount: BigInt(5_500_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "How photovoltaic cells convert sunlight to electricity — the photoelectric effect, semiconductors, and solar panel design.",
    topicSlugs: ["engineering"],
  },
  {
    platformId: "7a0GedFn-cU",
    platform: "YOUTUBE" as const,
    title: "The Ingenious Design of the Aluminum Beverage Can",
    description: "How do they make a can that holds carbonated liquid under pressure, survives drops, stacks for shipping, and uses almost no aluminum? Practical Engineering explores.",
    channelName: "Practical Engineering",
    thumbnailUrl: "https://i.ytimg.com/vi/7a0GedFn-cU/hqdefault.jpg",
    sourceUrl: "https://www.youtube.com/watch?v=7a0GedFn-cU",
    embedUrl: "https://www.youtube.com/embed/7a0GedFn-cU",
    durationSeconds: 660,
    viewCount: BigInt(4_000_000),
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    aiSummary: "Engineering genius hiding in plain sight — the remarkable design decisions behind the humble aluminum beverage can.",
    topicSlugs: ["engineering"],
  },
];

// ─── Learning Paths ───────────────────────────────────────────────────────────

const PATHS = [
  {
    title: "Python for Beginners",
    slug: "python-beginners",
    emoji: "🐍",
    description: "From zero to writing real programs. Start with freeCodeCamp's full course, then Mosh's project-based approach.",
    totalVideos: 2,
    totalSeconds: 37320,
    difficulty: "BEGINNER" as const,
    isFeatured: true,
    topicSlug: "programming",
    videoIds: ["rfscVS0vtbw", "_uQrJ0TkZlc"],
  },
  {
    title: "Full-Stack JavaScript Path",
    slug: "fullstack-javascript",
    emoji: "⚡",
    description: "Master JavaScript from basics to React — the essential modern web development stack.",
    totalVideos: 3,
    totalSeconds: 20520,
    difficulty: "BEGINNER" as const,
    isFeatured: true,
    topicSlug: "programming",
    videoIds: ["PkZNo7MFNFg", "RGOj5yH7evk", "Ke90Tje7VS0"],
  },
  {
    title: "The Essence of Mathematics",
    slug: "essence-of-mathematics",
    emoji: "∑",
    description: "Visual, intuitive math from 3Blue1Brown — vectors, calculus, and neural networks from first principles.",
    totalVideos: 3,
    totalSeconds: 2769,
    difficulty: "INTERMEDIATE" as const,
    isFeatured: true,
    topicSlug: "mathematics",
    videoIds: ["fNk_zzaMoSs", "WUvTyaaNkzM", "aircAruvnKk"],
  },
  {
    title: "TED: Ideas Worth Spreading",
    slug: "ted-ideas",
    emoji: "🎙️",
    description: "The most essential TED talks — on creativity, leadership, vulnerability, and the human condition.",
    totalVideos: 4,
    totalSeconds: 4309,
    difficulty: "BEGINNER" as const,
    isFeatured: true,
    topicSlug: "philosophy",
    videoIds: ["qp0HIF3SfI4", "iG9CE55wbtY", "iCvmsMzlF7o", "arj7oStGLkU"],
  },
  {
    title: "World History in a Flash",
    slug: "world-history",
    emoji: "🌍",
    description: "From the Big Bang through the Agricultural Revolution to the modern era — history made entertaining.",
    totalVideos: 4,
    totalSeconds: 3295,
    difficulty: "BEGINNER" as const,
    isFeatured: true,
    topicSlug: "history",
    videoIds: ["xuCn8ux2gbs", "Mh5LY4Mz15o", "Yocja_N5s1I", "_uk_6vfYy64"],
  },
  {
    title: "Finance 101",
    slug: "finance-101",
    emoji: "💸",
    description: "How the stock market works, how the economy runs, and the basics of personal investing.",
    totalVideos: 3,
    totalSeconds: 2340,
    difficulty: "BEGINNER" as const,
    isFeatured: true,
    topicSlug: "finance",
    videoIds: ["PHe0bXAIuk0", "p7HKvqRI_Bo", "3ez10ADR_gM"],
  },
  {
    title: "Understanding the Cosmos",
    slug: "understanding-cosmos",
    emoji: "🌌",
    description: "From black holes to neutron stars — Kurzgesagt's best explainers on the universe.",
    totalVideos: 3,
    totalSeconds: 1380,
    difficulty: "BEGINNER" as const,
    isFeatured: true,
    topicSlug: "astronomy",
    videoIds: ["e-P5IFTqB98", "udFxKZRyQt4", "Da-2h3F5a18"],
  },
  {
    title: "The Multilingual Mind",
    slug: "multilingual-mind",
    emoji: "🗣️",
    description: "How to learn languages faster and why bilingualism changes your brain.",
    totalVideos: 2,
    totalSeconds: 1380,
    difficulty: "BEGINNER" as const,
    isFeatured: false,
    topicSlug: "languages",
    videoIds: ["d0yGdNEWdn0", "MMmOLN5zBLY"],
  },
];

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log("🌱 Seeding database...\n");

  // 1. Upsert topics + subtopics
  const topicMap: Record<string, string> = {}; // slug → DB id

  for (const t of TOPICS) {
    const { subtopics, ...topicData } = t;
    const topic = await prisma.topic.upsert({
      where: { slug: topicData.slug },
      update: { name: topicData.name, emoji: topicData.emoji, color: topicData.color, videoCount: topicData.videoCount },
      create: topicData,
    });
    topicMap[topicData.slug] = topic.id;

    for (const sub of subtopics) {
      const subSlug = sub.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
      await prisma.subtopic.upsert({
        where: { slug_topicId: { slug: subSlug, topicId: topic.id } },
        update: {},
        create: { name: sub, slug: subSlug, topicId: topic.id },
      });
    }
    console.log(`  ✓ Topic: ${t.emoji} ${t.name}`);
  }

  // 2. Upsert videos + topic links
  const videoMap: Record<string, string> = {}; // platformId → DB id

  for (const v of VIDEOS) {
    const { topicSlugs, ...videoData } = v;
    const video = await prisma.video.upsert({
      where: { platformId_platform: { platformId: v.platformId, platform: v.platform } },
      update: { ...videoData },
      create: { ...videoData, isActive: true },
    });
    videoMap[v.platformId] = video.id;

    for (const slug of topicSlugs) {
      const topicId = topicMap[slug];
      if (topicId) {
        await prisma.videoTopic.upsert({
          where: { videoId_topicId: { videoId: video.id, topicId } },
          update: {},
          create: { videoId: video.id, topicId },
        });
      }
    }
    console.log(`  ✓ Video: ${v.title.substring(0, 55)}`);
  }

  // 3. Upsert learning paths + path videos
  for (const p of PATHS) {
    const { topicSlug, videoIds, ...pathData } = p;
    const topicId = topicMap[topicSlug] ?? null;

    const path = await prisma.learningPath.upsert({
      where: { slug: p.slug },
      update: { ...pathData, topicId },
      create: { ...pathData, topicId },
    });

    for (let i = 0; i < videoIds.length; i++) {
      const videoDbId = videoMap[videoIds[i]];
      if (!videoDbId) continue;
      await prisma.pathVideo.upsert({
        where: { pathId_videoId: { pathId: path.id, videoId: videoDbId } },
        update: { order: i + 1 },
        create: { pathId: path.id, videoId: videoDbId, order: i + 1 },
      });
    }
    console.log(`  ✓ Path: ${p.emoji} ${p.title}`);
  }

  console.log("\n✅ Seed complete!");
  console.log(`   ${TOPICS.length} topics · ${VIDEOS.length} videos · ${PATHS.length} paths`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
